name = "CPython"
description = "Python is a high-level, general-purpose programming language"

[colors]
foreground = 0xfed140
background = 0x3670a0

[run]
unix = "python3 {}"
windows = "py {}"

[dependencies]
unix = ["python3"]
windows = ["py"]
