name = "CPython"
description = "Python is a high-level, general-purpose programming language"

[colors]
foreground = "fed140"
background = "3670a0"

[run]
unix = "python3 {}"
windows = "py {}"

[dependencies]
unix = ["python3"]
windows = ["py"]
