name = "C"
description = "C (pronounced like the letter c) is a general-purpose computer programming language"

[colors]
foreground = "ffffff"
background = "00599d"

[build]
common = "gcc -o {out-file} {main-file}"

[run]
common = "{}"

[dependencies]
common = ["gcc"]
