name = "C"
description = "C (pronounced like the letter c) is a general-purpose computer programming language"

[color]
foreground = 0xffffff
background = 0x00599d

[build]
common = "gcc -o {out} {main}"

[run]
common = "{}"

[dependency]
common = ["gcc"]
